version: "3"
services:
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - 2345:5432
    env_file:
      - .env
    volumes:
      - pg:/var/lib/postgresql/data # aonde os dados do postgres ficam

  node_app:
    container_name: node_app
    build: . #Caminho para a Dockerfile
    ports:
      - 5000:5000
    env_file:
      - .env
    depends_on:
      - db # sรณ sobe quando o db tiver no ar
    volumes:
      - .:/usr/src
      - /usr/src/node_modules

volumes:
  pg:
