version: '3'
services:
    postgres:
        image: postgres
        container_name: postgres
        env_file:
            - .env.test

    node_app:
        build: .
        container_name: node_app
        env_file:
            - .env.test
        entrypoint: dockerize -wait tcp://postgres:5432 -timeout 20s docker-entrypoint.sh
        command: 'npm run test'
        depends_on:
            - postgres
