version: "3"
services:
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - 2345:5432
    env_file:
      - .env.test

  node_app:
    container_name: node_app
    build: . #Caminho para a Dockerfile
    ports:
      - 5000:5000
    env_file:
      - .env.test
    depends_on:
      - db # sรณ sobe quando o db tiver no ar
